name: Attest Build

on:
  workflow_run:
    workflows: ["Code Scan"]
    types:
      - completed

jobs:
  check_and_attest:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download result artifact
        uses: actions/download-artifact@v4
        with:
          name: scan-result

      - name: Check if critical findings were found
        id: gate
        run: |
          status=$(cat result.txt)
          echo "Scan result: $status"
          if [[ "$status" == "true" ]]; then
            echo "Critical issues found. Skipping attestation."
            exit 1
          fi

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR
        run: mvn clean package --no-transfer-progress
    
      - name: Find built artifact
        id: locate-artifact
        run: |
          ARTIFACT=$(find target -type f -name "*.war" | head -n 1)
          echo "artifact_path=$ARTIFACT" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ${{ steps.locate-artifact.outputs.artifact_path }}

      - name: Generate SLSA Provenance
        uses: slsa-framework/slsa-github-generator/actions/provenance@v2.1.0
        with:
          artifact_path: ${{ steps.locate-artifact.outputs.artifact_path }}