name: Snyk Maven Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (optional)
        run: mvn -B compile

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash
          echo "$HOME/.snyk" >> $GITHUB_PATH

      - name: Authenticate with Snyk
        run: snyk auth "${{ secrets.SNYK_TOKEN }}"

      - name: Run Snyk Open Source scan with SARIF output
        continue-on-error: true
        run: |
          snyk test --all-projects --org="${{ secrets.SNYK_ORG }}" 
      - name: Run Snyk Code (static analysis)
        continue-on-error: true
        run: snyk code test --org="${{ secrets.SNYK_ORG }}" --sarif-file-output=snyk-results.sarif

     # - name: Monitor project for continuous integration
      #  run: snyk monitor --all-projects --org="${{ secrets.SNYK_ORG }}"

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif
