name: Snyk Maven Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - uses: snyk/actions/setup@master
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Verify Java setup
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          echo "Java binary: $(which java)"
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (optional)
        run: mvn -B compile

      - name: Run Snyk Open Source scan 
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --org="${{ secrets.SNYK_ORG }}"
        continue-on-error: true
  
      - name: Run Snyk Code (static analysis)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --org="${{ secrets.SNYK_ORG }}" --sarif-file-output=snyk.sarif
        continue-on-error: true
     # - name: Monitor project for continuous integration
      #  run: snyk monitor --all-projects --org="${{ secrets.SNYK_ORG }}"

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Check for critical code scanning alerts
        id: check_critical
        run: |
          owner="${{ github.repository_owner }}"
          repo="${{ github.event.repository.name }}"
          alerts=$(gh api "/repos/$owner/$repo/code-scanning/alerts" --paginate --jq '.[] | select(.rule.severity=="critical")')
          if [[ -n "$alerts" ]]; then
            echo "Critical alerts found"
            echo "critical_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "No critical alerts"
            echo "critical_found=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
  attest:
    name: Build Provenance Attestation
    needs: snyk_scan
    if: needs.scan.outputs.critical_found == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Attest
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-path: 'target'
