name: Snyk Maven Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - uses: snyk/actions/setup@master
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (optional)
        run: mvn -B compile

      - name: Run Snyk Open Source scan 
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --org="${{ secrets.SNYK_ORG }}"
        continue-on-error: true
  
      - name: Run Snyk Code (static analysis)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --org="${{ secrets.SNYK_ORG }}" --sarif-file-output=snyk.sarif
        continue-on-error: true
     # - name: Monitor project for continuous integration
      #  run: snyk monitor --all-projects --org="${{ secrets.SNYK_ORG }}"

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
